### PR TITLE
Change mixpanel project to tandem_splash.

### PR DESCRIPTION
**Pull request by stephenthoma**
Looks like we accidentally had the same project for both sites. This fixes that. (unless you guys meant to do that?)

### CODE REVIEW

**Comment by Zandrr** [comment]
We meant to do it, just named events differently.  Either way works though

**Comment by thejinxters** [comment]
Since you already did it, you might as well have it separate.

**Comment by stephenthoma** [comment]
:shipit:? I think it could be useful to have it separate in the long run

**Comment by thejinxters** [comment]
:+1:

**Pull request merged**
